name: vinexplainnet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch>=2.2
  - numpy>=1.26
  - scipy>=1.11
  - scikit-learn>=1.3
  - pip
  - pip:
      - argh>=0.31
      - pyhocon>=0.3.61
