from __future__ import annotations

import ast
import re
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "vinexplainnet"

FORBIDDEN = (
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "skeleton",
    "placeholder",
    "todo from paper",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
    "state-of-the-art",
)

EMOJI = re.compile("[\U0001f000-\U0001faff☀-➿←-⇿⬀-⯿]")


def _python_files() -> list[Path]:
    return sorted(PACKAGE.rglob("*.py"))


def _prose_files() -> list[Path]:
    return _python_files() + [ROOT / "README.md", ROOT / "Makefile"]


def test_no_inline_comments() -> None:
    for path in _python_files():
        with open(path, encoding="utf-8") as handle:
            for token in tokenize.generate_tokens(handle.readline):
                assert token.type != tokenize.COMMENT, f"comment in {path}"


def test_no_docstrings() -> None:
    for path in _python_files():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Module | ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                assert ast.get_docstring(node) is None, f"docstring in {path}"


def test_no_forbidden_phrases() -> None:
    for path in _prose_files():
        text = path.read_text(encoding="utf-8").lower()
        for phrase in FORBIDDEN:
            assert phrase not in text, f"{phrase!r} in {path}"


def test_no_emoji() -> None:
    for path in _prose_files():
        assert EMOJI.search(path.read_text(encoding="utf-8")) is None, f"emoji in {path}"
